# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGUI.ui'
#
# Created: Sun Aug  6 20:30:33 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_BB_Heatmap_Viewer(object):
    def setupUi(self, BB_Heatmap_Viewer):
        BB_Heatmap_Viewer.setObjectName("BB_Heatmap_Viewer")
        BB_Heatmap_Viewer.resize(820, 940)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BB_Heatmap_Viewer.sizePolicy().hasHeightForWidth())
        BB_Heatmap_Viewer.setSizePolicy(sizePolicy)
        BB_Heatmap_Viewer.setMinimumSize(QtCore.QSize(820, 940))
        BB_Heatmap_Viewer.setMaximumSize(QtCore.QSize(1500, 1500))
        self.centralwidget = QtGui.QWidget(BB_Heatmap_Viewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SelectHeatmapFileButton = QtGui.QPushButton(self.centralwidget)
        self.SelectHeatmapFileButton.setObjectName("SelectHeatmapFileButton")
        self.verticalLayout_3.addWidget(self.SelectHeatmapFileButton)
        self.SelectHeatmapBackgroundButton = QtGui.QPushButton(self.centralwidget)
        self.SelectHeatmapBackgroundButton.setObjectName("SelectHeatmapBackgroundButton")
        self.verticalLayout_3.addWidget(self.SelectHeatmapBackgroundButton)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label2 = QtGui.QLabel(self.centralwidget)
        self.label2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2.setObjectName("label2")
        self.horizontalLayout_2.addWidget(self.label2)
        self.HeatmapPathLabel = QtGui.QLabel(self.centralwidget)
        self.HeatmapPathLabel.setObjectName("HeatmapPathLabel")
        self.horizontalLayout_2.addWidget(self.HeatmapPathLabel)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.HeatmapSceneNameLabel = QtGui.QLabel(self.centralwidget)
        self.HeatmapSceneNameLabel.setObjectName("HeatmapSceneNameLabel")
        self.horizontalLayout_4.addWidget(self.HeatmapSceneNameLabel)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.CurrentBackgroundPathLabel = QtGui.QLabel(self.centralwidget)
        self.CurrentBackgroundPathLabel.setObjectName("CurrentBackgroundPathLabel")
        self.horizontalLayout_7.addWidget(self.CurrentBackgroundPathLabel)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Time_Radio = QtGui.QRadioButton(self.groupBox)
        self.Time_Radio.setChecked(True)
        self.Time_Radio.setObjectName("Time_Radio")
        self.horizontalLayout.addWidget(self.Time_Radio)
        self.Entries_Radio = QtGui.QRadioButton(self.groupBox)
        self.Entries_Radio.setChecked(False)
        self.Entries_Radio.setObjectName("Entries_Radio")
        self.horizontalLayout.addWidget(self.Entries_Radio)
        self.Scores_Radio = QtGui.QRadioButton(self.groupBox)
        self.Scores_Radio.setChecked(False)
        self.Scores_Radio.setObjectName("Scores_Radio")
        self.horizontalLayout.addWidget(self.Scores_Radio)
        self.Throws_Radio = QtGui.QRadioButton(self.groupBox)
        self.Throws_Radio.setChecked(False)
        self.Throws_Radio.setObjectName("Throws_Radio")
        self.horizontalLayout.addWidget(self.Throws_Radio)
        self.Dashes_Radio = QtGui.QRadioButton(self.groupBox)
        self.Dashes_Radio.setChecked(False)
        self.Dashes_Radio.setObjectName("Dashes_Radio")
        self.horizontalLayout.addWidget(self.Dashes_Radio)
        self.Stuns_Radio = QtGui.QRadioButton(self.groupBox)
        self.Stuns_Radio.setChecked(False)
        self.Stuns_Radio.setObjectName("Stuns_Radio")
        self.horizontalLayout.addWidget(self.Stuns_Radio)
        self.Punches_Radio = QtGui.QRadioButton(self.groupBox)
        self.Punches_Radio.setChecked(False)
        self.Punches_Radio.setObjectName("Punches_Radio")
        self.horizontalLayout.addWidget(self.Punches_Radio)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Draw_Area = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Draw_Area.sizePolicy().hasHeightForWidth())
        self.Draw_Area.setSizePolicy(sizePolicy)
        self.Draw_Area.setMinimumSize(QtCore.QSize(800, 800))
        self.Draw_Area.setMaximumSize(QtCore.QSize(800, 800))
        self.Draw_Area.setFrameShape(QtGui.QFrame.Box)
        self.Draw_Area.setText("")
        self.Draw_Area.setObjectName("Draw_Area")
        self.gridLayout_2.addWidget(self.Draw_Area, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.setStretch(2, 10)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        BB_Heatmap_Viewer.setCentralWidget(self.centralwidget)

        self.retranslateUi(BB_Heatmap_Viewer)
        QtCore.QMetaObject.connectSlotsByName(BB_Heatmap_Viewer)

    def retranslateUi(self, BB_Heatmap_Viewer):
        BB_Heatmap_Viewer.setWindowTitle(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Bargain Bash Heatmap Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectHeatmapFileButton.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Select Heatmap File", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectHeatmapBackgroundButton.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Select Heatmap Background", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Current Heatmap File:", None, QtGui.QApplication.UnicodeUTF8))
        self.HeatmapPathLabel.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Heatmap Scene:", None, QtGui.QApplication.UnicodeUTF8))
        self.HeatmapSceneNameLabel.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Current Backgound File:", None, QtGui.QApplication.UnicodeUTF8))
        self.CurrentBackgroundPathLabel.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Statistic to Display", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_Radio.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.Entries_Radio.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Entries", None, QtGui.QApplication.UnicodeUTF8))
        self.Scores_Radio.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Scores", None, QtGui.QApplication.UnicodeUTF8))
        self.Throws_Radio.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Throws", None, QtGui.QApplication.UnicodeUTF8))
        self.Dashes_Radio.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Dashes", None, QtGui.QApplication.UnicodeUTF8))
        self.Stuns_Radio.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Stuns", None, QtGui.QApplication.UnicodeUTF8))
        self.Punches_Radio.setText(QtGui.QApplication.translate("BB_Heatmap_Viewer", "Punches", None, QtGui.QApplication.UnicodeUTF8))

